#!/bin/bash

# FaceAISDK_RN 自动化运行脚本
# 适配 iOS 和 Android 真机
# 注意：在 iOS 真机运行时，请确保已经在 Xcode 的 Signing & Capabilities 中手动选择了一次 Team（开发人员证书），否则 Apple 会拒绝安装未签名的 App 到手机上

set -u
set -o pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$ROOT_DIR/.." && pwd)"
IOS_DIR="$ROOT_DIR/ios"
IOS_DERIVED_DATA_DIR="$ROOT_DIR/.build/ios"
ENSURE_DEPS_SCRIPT="$ROOT_DIR/ensure-js-deps.sh"
ANDROID_RUN_LOG="/tmp/facern-android-run.log"
HAS_FAILURE=0

cd "$ROOT_DIR" || exit 1

echo "========================================"
echo "   FaceAISDK_RN 快速运行工具"
echo "========================================"

ensure_example_js_deps() {
    bash "$ENSURE_DEPS_SCRIPT"
}

detect_android_sdk() {
    local candidates=()
    local sdk_path=""

    if [ -f "android/local.properties" ]; then
        sdk_path=$(sed -n 's/^sdk\.dir=//p' android/local.properties | tail -n 1)
        sdk_path=${sdk_path//\\:/:}
        sdk_path=${sdk_path//\\//}
        [ -n "$sdk_path" ] && candidates+=("$sdk_path")
    fi

    [ -n "${ANDROID_SDK_ROOT:-}" ] && candidates+=("$ANDROID_SDK_ROOT")
    [ -n "${ANDROID_HOME:-}" ] && candidates+=("$ANDROID_HOME")
    candidates+=("$HOME/Library/Android/sdk")
    candidates+=("$HOME/Library/Developer/AndroidSDK")

    if command -v adb > /dev/null 2>&1; then
        sdk_path="$(cd "$(dirname "$(command -v adb)")/.." && pwd)"
        candidates+=("$sdk_path")
    fi

    for sdk_path in "${candidates[@]}"; do
        if [ -x "$sdk_path/platform-tools/adb" ]; then
            echo "$sdk_path"
            return 0
        fi
    done

    return 1
}

configure_android_sdk() {
    local sdk_path=""
    sdk_path="$(detect_android_sdk || true)"

    if [ -z "$sdk_path" ]; then
        return 1
    fi

    export ANDROID_HOME="$sdk_path"
    export ANDROID_SDK_ROOT="$sdk_path"

    case ":$PATH:" in
        *":$sdk_path/platform-tools:"*) ;;
        *) export PATH="$sdk_path/platform-tools:$sdk_path/emulator:$PATH" ;;
    esac

    echo "sdk.dir=$sdk_path" > android/local.properties
    echo "✅ Android SDK 已设置为: $sdk_path"
    return 0
}

start_metro() {
    if lsof -iTCP:8081 -sTCP:LISTEN > /dev/null 2>&1; then
        echo "✅ Metro 已在 8081 端口运行。"
        return 0
    fi

    echo "▶️  后台启动 Metro 服务端..."
    nohup node "$REPO_DIR/node_modules/react-native/cli.js" start --config "$ROOT_DIR/metro.config.js" > /tmp/facern-metro.log 2>&1 &
    sleep 5

    if lsof -iTCP:8081 -sTCP:LISTEN > /dev/null 2>&1; then
        echo "✅ Metro 启动成功。日志: /tmp/facern-metro.log"
    else
        echo "⚠️  Metro 可能尚未完全启动，请查看日志: /tmp/facern-metro.log"
    fi
}

find_ios_device() {
    python3 <<'PY'
import json
import subprocess
import sys

try:
    raw = subprocess.check_output(["xcrun", "xcdevice", "list"], stderr=subprocess.DEVNULL)
    items = json.loads(raw.decode("utf-8"))
except Exception:
    sys.exit(1)

for item in items:
    if item.get("simulator"):
        continue
    if not item.get("available"):
        continue
    platform = item.get("platform")
    if platform and platform != "com.apple.platform.iphoneos":
        continue

    name = item.get("name")
    identifier = item.get("identifier")
    if name and identifier:
        print(name)
        print(identifier)
        sys.exit(0)

sys.exit(1)
PY
}

sync_xcode_node_binary() {
    local node_path=""
    local node_dir=""

    node_path="$(command -v node 2> /dev/null || true)"
    if [ -z "$node_path" ]; then
        echo "❌ 未找到 node，可先确认 Node.js / nvm 环境是否已安装。"
        return 1
    fi

    node_dir="$(dirname "$node_path")"
    cat > "$IOS_DIR/.xcode.env.local" <<EOF
# Auto-generated by auto_run.sh
export NODE_BINARY="$node_path"
export PATH="$node_dir:\$PATH"
EOF

    echo "✅ Xcode Node 路径已同步为: $node_path"
    return 0
}

ensure_ios_pods() {
    if [ -d "$IOS_DIR/Pods" ] && [ -d "$IOS_DIR/FaceRN.xcworkspace" ]; then
        return 0
    fi

    echo "📦 安装 iOS 依赖库 (pod install)..."
    "$ROOT_DIR/pod-install.sh"
}

build_and_launch_ios() {
    local ios_name="$1"
    local ios_udid="$2"
    local app_path="$IOS_DERIVED_DATA_DIR/Build/Products/Debug-iphoneos/FaceRN.app"
    local ios_deploy_log="/tmp/facern-ios-deploy.log"

    if [ ! -d "$IOS_DIR/FaceRN.xcworkspace" ]; then
        echo "❌ 未找到 iOS workspace: $IOS_DIR/FaceRN.xcworkspace"
        return 1
    fi

    mkdir -p "$IOS_DERIVED_DATA_DIR"

    echo "🏗️  正在通过 xcodebuild 为 iOS 真机构建应用..."
    (
        cd "$IOS_DIR" && \
        xcodebuild \
            -workspace "FaceRN.xcworkspace" \
            -scheme "FaceRN" \
            -configuration Debug \
            -destination "id=$ios_udid" \
            -derivedDataPath "$IOS_DERIVED_DATA_DIR" \
            -allowProvisioningUpdates \
            build
    ) || return 1

    if [ ! -d "$app_path" ]; then
        echo "❌ 已完成构建，但未找到生成的 .app 包: $app_path"
        return 1
    fi

    echo "🚀 正在使用 ios-deploy 安装并启动到 $ios_name ..."
    if ! "$REPO_DIR/node_modules/.bin/ios-deploy" \
        --id "$ios_udid" \
        --bundle "$app_path" \
        --justlaunch \
        --noninteractive \
        --unbuffered \
        --no-wifi 2>&1 | tee "$ios_deploy_log"; then
        if grep -q "device was not, or could not be, unlocked" "$ios_deploy_log"; then
            echo "❌ iOS App 已安装到设备，但启动失败：手机当前未解锁。请解锁 iPhone 后重试。"
        else
            echo "❌ ios-deploy 安装/启动失败，请查看日志: $ios_deploy_log"
        fi
        return 1
    fi

    if grep -q "device was not, or could not be, unlocked" "$ios_deploy_log"; then
        echo "❌ iOS App 已安装到设备，但启动失败：手机当前未解锁。请解锁 iPhone 后重试。"
        return 1
    fi

    echo "✅ iOS App 已完成安装并触发启动。"
}

echo "⚙️  检查 Example JavaScript 依赖..."
if ! ensure_example_js_deps; then
    echo "❌ Example JavaScript 依赖安装失败，请查看上方日志。"
    exit 1
fi

echo "⚙️  检查 Android SDK 配置..."
if ! configure_android_sdk; then
    echo "⚠️  未找到可用的 Android SDK，请检查 Android Studio SDK 安装。"
fi

start_metro

echo -e "\n🤖 正在检测 Android 真机..."
if command -v adb > /dev/null 2>&1 && adb devices | awk 'NR > 1 && $2 == "device" { found = 1 } END { exit !found }'; then
    ANDROID_DEVICE_ID="$(adb devices | awk 'NR > 1 && $2 == "device" { print $1; exit }')"
    echo "✅ 发现 Android 设备: $ANDROID_DEVICE_ID"
    adb reverse tcp:8081 tcp:8081 > /dev/null 2>&1 || true
    if ! node "$REPO_DIR/node_modules/react-native/cli.js" run-android --device "$ANDROID_DEVICE_ID" --no-packager 2>&1 | tee "$ANDROID_RUN_LOG"; then
        HAS_FAILURE=1
        echo "❌ Android 启动失败，请查看上方日志。"
        echo "   完整日志: $ANDROID_RUN_LOG"
        grep -E "(^FAILURE:|^\\* What went wrong:|Execution failed|INSTALL_FAILED|Duplicate class|defined multiple times|Unresolved reference|error )" "$ANDROID_RUN_LOG" | tail -n 20 || true
    fi
else
    echo "❌ 未发现 Android 真机，请检查 USB 调试是否开启。"
fi

echo -e "\n🍎 正在检测 iOS 真机..."
IOS_DEVICE_INFO="$(find_ios_device || true)"
IOS_DEVICE_NAME="$(printf '%s\n' "$IOS_DEVICE_INFO" | sed -n '1p')"
IOS_DEVICE_UDID="$(printf '%s\n' "$IOS_DEVICE_INFO" | sed -n '2p')"

if [ -n "$IOS_DEVICE_NAME" ] && [ -n "$IOS_DEVICE_UDID" ]; then
    echo "✅ 发现 iOS 设备: $IOS_DEVICE_NAME"
    echo "✅ UDID: $IOS_DEVICE_UDID"
    echo "ℹ️ 提示：首次运行请确保已在 Xcode 中配置好 Signing & Team。"
    echo "ℹ️ 如使用 Xcode 15.x，本脚本会自动应用 RCTSwiftUI 的 swiftinterface 校验兼容处理。"

    if ! sync_xcode_node_binary || ! ensure_ios_pods || ! build_and_launch_ios "$IOS_DEVICE_NAME" "$IOS_DEVICE_UDID"; then
        HAS_FAILURE=1
    fi
else
    echo "❌ 未发现可用的 iOS 真机，请通过数据线连接、解锁手机并点击「信任此电脑」。"
fi

echo -e "\n========================================"
if [ "$HAS_FAILURE" -eq 0 ]; then
    echo "   任务提交完成，请在手机上查看运行结果"
else
    echo "   任务已执行，但存在失败项，请查看上方日志"
fi
echo "========================================"
