import type { AddFaceBySDKCameraOptions, FaceResult, FaceVerifyOptions, LivenessVerifyOptions } from './types';
export declare const FACE_AI_STATUS_CODE_MAP: Record<number, string>;
export declare function isFaceAIModuleAvailable(): boolean;
export declare function addFaceBySDKCamera(faceID: string, options?: AddFaceBySDKCameraOptions): Promise<FaceResult>;
export declare function faceVerify(faceID: string, options?: FaceVerifyOptions): Promise<FaceResult>;
export declare function livenessVerify(options?: LivenessVerifyOptions): Promise<FaceResult>;
export declare function getFaceFeature(faceID: string): Promise<FaceResult>;
export declare function insertFaceFeature(faceID: string, faceFeature: string): Promise<FaceResult>;
export declare function addFaceByImage(faceID: string, base64Image: string): Promise<FaceResult>;
export declare function deleteFaceFeature(faceID: string): Promise<FaceResult>;
export type { AddFaceBySDKCameraOptions, FaceResult, FaceVerifyOptions, LivenessVerifyOptions, } from './types';
declare const _default: {
    addFaceBySDKCamera: typeof addFaceBySDKCamera;
    faceVerify: typeof faceVerify;
    livenessVerify: typeof livenessVerify;
    getFaceFeature: typeof getFaceFeature;
    insertFaceFeature: typeof insertFaceFeature;
    addFaceByImage: typeof addFaceByImage;
    deleteFaceFeature: typeof deleteFaceFeature;
    isFaceAIModuleAvailable: typeof isFaceAIModuleAvailable;
};
export default _default;
