import Foundation
import SwiftUI

// 1. 如果想改变主题颜色
extension Color {
    /// 主题颜色 #347738 ，用AI换算一下
    static var faceMain: Color {
        return Color(red: 52 / 255.0, green: 119 / 255.0, blue: 56 / 255.0)
    }
}

@objcMembers
public final class FaceSDKLocalizer: NSObject {
    private static let zhHans: [String: String] = [
        "About us": "关于我们",
        "Add Face By Camera": "SDK相机添加人脸",
        "Add Face From Album": "从相册添加一人脸",
        "Confirm": "确认",
        "Confirm Add Face": "确认录入此人脸图？",
        "Ensure face is clear": "请录入无遮挡正脸清晰图",
        "Face Verify & Liveness": "人脸识别+活体检测",
        "I Know": "知道了",
        "Is Face Feature Exist": "人脸特征值是否存在",
        "ONLY Liveness Detection": "仅仅活体检测",
        "Retry": "重试",
        "Save Face Feature": "保存人脸特征",
        "Select from album": "从相册选择",
        "Select Image": "选择图片",
        "Verify Two Face Similarity": "静态人脸相似度对比",
        "No Face Feature for : %@": "%@ 没有可用人脸特征值",
        "Invalid Feature length for : %@": "%@ 的人脸特征长度无效",
        "User canceled/interrupted": "用户取消/中断操作",
        "Operation succeeded": "操作成功",
        "Low face similarity (verification failed)": "人脸相似度过低(认证失败)",
        "Motion liveness passed": "动作活体检测成功",
        "Motion liveness timeout": "动作活体检测超时",
        "No face detected repeatedly": "多次未检测到人脸",
        "No local face feature found": "本地无对应人脸特征值",
        "Color liveness passed": "炫彩活体成功",
        "Color liveness failed": "炫彩活体失败",
        "Ambient light too strong (color failed)": "环境光线过强(炫彩失败)",
        "All liveness checks passed": "活体检测全部通过",
        "Silent liveness failed": "静默活体检测失败",
        "No enrolled face information": "没有录入人脸信息",
        "Multiple faces detected": "多个人脸入境",
        "Unknown status code": "未知状态码",
        "Face enrollment succeeded": "人脸录入成功",
        "User canceled enrollment": "用户取消录入",
        "Delete Success": "删除成功",
        "Base64 image parse failed": "图片Base64解析失败",
        "Face feature extracted successfully, length: %ld": "提取人脸特征成功，长度：%ld",
        "Unable to extract face feature, ensure image is clear and contains a face": "未能提取到人脸特征，请确保图片清晰且包含人脸",
        "Feature length only %ld": "特征值长度仅 %ld",
        "Face sync succeeded": "人脸同步成功",
        "Feature length=%ld": "feature 长度=%ld",
        "Face_Tips_Code_-1": "FaceSDK Version Too Old",
        "Face_Tips_Code_(code)": "error",
        "Face_Tips_Code_0": "请正对摄像头",
        "Face_Tips_Code_1": "没有检测到人脸",
        "Face_Tips_Code_2": "检测到多个人脸",
        "Face_Tips_Code_3": "请靠近一点",
        "Face_Tips_Code_4": "保持正脸不要晃动",
        "Face_Tips_Code_5": "不要闭眼睛",
        "Face_Tips_Code_6": "向右摆正头部",
        "Face_Tips_Code_7": "向左摆正头部",
        "Face_Tips_Code_8": "不要歪头",
        "Face_Tips_Code_9": "向上摆正头部",
        "Face_Tips_Code_10": "向下摆正头部",
        "Face_Tips_Code_11": "人脸采集确认",
        "Face_Tips_Code_12": " ",
        "Face_Tips_Code_13": "人脸太小了",
        "Face_Tips_Code_31": "没有找到对应的人脸底片",
        "Face_Tips_Code_32": "人脸底片处理失败",
        "Face_Tips_Code_33": "SDK 内部错误",
        "Face_Tips_Code_34": "动作活体检测完成",
        "Face_Tips_Code_35": "动作活体检验超时",
        "Face_Tips_Code_38": "多次切换人脸或检测失败",
        "Face_Tips_Code_41": "请张张嘴",
        "Face_Tips_Code_42": "请微笑",
        "Face_Tips_Code_43": "请眨眼",
        "Face_Tips_Code_44": "请摇头",
        "Face_Tips_Code_45": "请点头",
        "Face_Tips_Code_50": "请靠近,屏幕即将闪烁",
        "Face_Tips_Code_51": "炫彩活体成功",
        "Face_Tips_Code_52": "炫彩活体失败",
        "Face_Tips_Code_53": "炫彩活体检测失败,光线亮度过高;如图遮挡高亮光源或室内光线柔和环境使用",
        "Face_Tips_Code_58": "光线过强,避免强光照射",
        "Face_Tips_Code_60": "活体检测失败,请确认光线环境柔和",
        "Face_Tips_Code_61": "活体检测完成",
        "Face_Tips_Code_62": "人脸识别成功",
        "Face_Tips_Code_63": "人脸识别失败"
    ]

    private static let en: [String: String] = [
        "About us": "About us",
        "Add Face By Camera": "Add Face By Camera",
        "Add Face From Album": "Add Face From Album",
        "Confirm": "Confirm",
        "Confirm Add Face": "Confirm Add Face",
        "Ensure face is clear": "Ensure face is clear",
        "Face Verify & Liveness": "Face Verify & Liveness",
        "I Know": "I Know",
        "Is Face Feature Exist": "Is Face Feature Exist",
        "ONLY Liveness Detection": "ONLY Liveness Detection",
        "Retry": "Retry",
        "Save Face Feature": "Save Face Feature",
        "Select from album": "Select from album",
        "Select Image": "Select Image",
        "Verify Two Face Similarity": "Verify Two Face Similarity",
        "No Face Feature for : %@": "No Face Feature for : %@",
        "Invalid Feature length for : %@": "Invalid Feature length for : %@",
        "User canceled/interrupted": "User canceled/interrupted",
        "Operation succeeded": "Operation succeeded",
        "Low face similarity (verification failed)": "Low face similarity (verification failed)",
        "Motion liveness passed": "Motion liveness passed",
        "Motion liveness timeout": "Motion liveness timeout",
        "No face detected repeatedly": "No face detected repeatedly",
        "No local face feature found": "No local face feature found",
        "Color liveness passed": "Color liveness passed",
        "Color liveness failed": "Color liveness failed",
        "Ambient light too strong (color failed)": "Ambient light too strong (color failed)",
        "All liveness checks passed": "All liveness checks passed",
        "Silent liveness failed": "Silent liveness failed",
        "No enrolled face information": "No enrolled face information",
        "Multiple faces detected": "Multiple faces detected",
        "Unknown status code": "Unknown status code",
        "Face enrollment succeeded": "Face enrollment succeeded",
        "User canceled enrollment": "User canceled enrollment",
        "Delete Success": "Delete Success",
        "Base64 image parse failed": "Base64 image parse failed",
        "Face feature extracted successfully, length: %ld": "Face feature extracted successfully, length: %ld",
        "Unable to extract face feature, ensure image is clear and contains a face": "Unable to extract face feature, ensure image is clear and contains a face",
        "Feature length only %ld": "Feature length only %ld",
        "Face sync succeeded": "Face sync succeeded",
        "Feature length=%ld": "Feature length=%ld",
        "Face_Tips_Code_-1": "FaceSDK Version Too Old",
        "Face_Tips_Code_(code)": "error",
        "Face_Tips_Code_0": "Keep Face Frontal",
        "Face_Tips_Code_1": "No Face Detected",
        "Face_Tips_Code_2": "Detect Too Many Face",
        "Face_Tips_Code_3": "Please Come Closer",
        "Face_Tips_Code_4": "Keep Face Frontal Visible",
        "Face_Tips_Code_5": "Do not Close Eye",
        "Face_Tips_Code_6": "Turn Face Right",
        "Face_Tips_Code_7": "Turn Face Left",
        "Face_Tips_Code_8": "Do not Tile Face",
        "Face_Tips_Code_9": "Turn Face Up",
        "Face_Tips_Code_10": "Turn Face Down",
        "Face_Tips_Code_11": "Confirm Add Face",
        "Face_Tips_Code_12": " ",
        "Face_Tips_Code_13": "Too Small Face",
        "Face_Tips_Code_31": "Face Image Not Found",
        "Face_Tips_Code_32": "Face Image Dispose Failed",
        "Face_Tips_Code_33": "SDK Error",
        "Face_Tips_Code_34": "Motion Liveness Complete",
        "Face_Tips_Code_35": "Motion Liveness Timeout",
        "Face_Tips_Code_38": "No Face Detected Multi Time",
        "Face_Tips_Code_41": "Open Mouse",
        "Face_Tips_Code_42": "Please Smile",
        "Face_Tips_Code_43": "Please Blink",
        "Face_Tips_Code_44": "Please Shake Head",
        "Face_Tips_Code_45": "Please Nod Head",
        "Face_Tips_Code_50": "Start Color Flash",
        "Face_Tips_Code_51": "Color Flash Success",
        "Face_Tips_Code_52": "Color Flash Failed",
        "Face_Tips_Code_53": "Detection failed: Too bright.Please avoid direct light as below and use in a softly lit indoor environment",
        "Face_Tips_Code_58": "Excessive light, avoid strong light exposure.",
        "Face_Tips_Code_60": "Liveness check failed. Please ensure soft lighting conditions",
        "Face_Tips_Code_61": "Face Liveness Success",
        "Face_Tips_Code_62": "Face Verify Success",
        "Face_Tips_Code_63": "Face Verify Failed"
    ]

    private class func currentTable() -> [String: String] {
        let preferredLanguage = Locale.preferredLanguages.first?.lowercased() ?? "en"
        return preferredLanguage.hasPrefix("zh") ? zhHans : en
    }

    public class func text(_ key: String) -> String {
        text(key, defaultValue: key)
    }

    public class func text(_ key: String, defaultValue: String) -> String {
        currentTable()[key] ?? defaultValue
    }
}