# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.5'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FaceAISDK_RN' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FaceAISDK_RNTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # 1. 执行 React Native 标准的后置处理
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # 2. 统一处理冲突的配置
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # 统一最低支持版本
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'

        # 彻底解决 "Can't merge user_target_xcconfig" 冲突
        # 移除 Pod 中可能冲突的 EXCLUDED_ARCHS 设置，由主项目统一管理
        config.build_settings.delete 'EXCLUDED_ARCHS[sdk=iphonesimulator*]'

        # 针对真机编译的必要设置
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end


end
